# -*- coding: utf-8 -*-
"""Position comparison.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkbHbz4mI7CTEVTF1xvFkaUo7jrzq0fE
"""

from scipy.spatial import distance

top_left = [20,30]
bottom_right = [50,70]

def compare_position(p1,p2):
  euclid_d1 = distance.euclidean(top_left, p1)
  euclid_d2 = distance.euclidean(bottom_right, p2)

  if (euclid_d1 == 0.0) & (euclid_d2 == 0.0):
    return 1
  
  else:
    return 0