# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkQ3FMeLHH8zPA08SszYvsi9sAliY-SV
"""

from pdf2image import convert_from_path

"""To check if the file uploaded is in pdf format"""

def check_pdf(filename):
  if filename.endswith(".pdf"):
    return 1
    
  else:
    return 0

"""Convert PDF to JPEG"""

def pdf_to_jgp(filename):
  pages = convert_from_path(filename, 500)
  for page in pages:
    page.save('out.jpg', 'JPEG')

def main():
  filename = r" "

  check_p = check_pdf(filename)

  if check_p == 1:
    pdf_to_jgp(filename)

if __name__ == '__main__':
  main()